Models/Noticias.cs
using System.ComponentModel.DataAnnotations;
using System.Security.AccessControl;
using System.Collections.Generic;
namespace Practica_2.Models
{
    public class Noticias
    {
        public int Id {get; set;}
         [Required]
        [Display(Name = "Título")]
        public string Titulo {get; set;}
        public string Posteo {get; set;}

        [Required]
        [Display(Name = "Descripción")]
        public string Descripcion {get; set;}
        public int VeterinariaId {get; set;}
        public Veterinaria Veterinaria {get; set;}
    }
}

Controllers/NoticiasController.cs
using System.ComponentModel;
using System.Diagnostics;
using System.Net.Http.Headers;
using System.Security.AccessControl;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Practica_2.Models;
using Practica_2.ViewModels;
namespace Practica_2.Controllers
{
    public class NoticiasController : Controller
    {
        private AppDbContext _context;
        public NoticiasController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(int id)
        {
            var veter = await _context.Veterinarias.Where(x => x.Id == id).Include(x => x.Noticias).FirstAsync();
            return PartialView("~/Views/Vet/Noticias.cshtml", veter);
        }
        public async Task<IActionResult> Guardar(Noticias model){
            if(ModelState.IsValid){
                model.Posteo = DateTime.Now.Date.ToShortDateString();
                _context.Noticias.Add(model);
                await _context.SaveChangesAsync();
                return Redirect("/Vet/Details/" + model.VeterinariaId);
            }
            return Redirect("/Vet/Index");
            
        }
    }
}

Controllers/VetController.cs
using System.ComponentModel;
using System.Diagnostics;
using System.Net.Http.Headers;
using System.Security.AccessControl;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Practica_2.Models;
using Practica_2.ViewModels;
namespace Practica_2.Controllers
{
    public class VetController : Controller
    {
        public List<Veterinaria> listVeterinaria = null;
        public List<Noticias> listNoticias = null;
        private AppDbContext _context;
        public VetController(AppDbContext context)
        {
            _context = context;
            /*var jsonString = System.IO.File.ReadAllText("Models/Veterinaria.json");
            listVeterinaria = JsonConvert.DeserializeObject<List<Veterinaria>>(jsonString);
            var jsonString = System.IO.File.ReadAllText("Models/Noticias.json");
            listNoticias = JsonConvert.DeserializeObject<List<Noticias>>(jsonString);*/
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin_Edit_Del")]
        public async Task<IActionResult> Editar(int? Id, Veterinaria model){
            if(Id == null){
                return NotFound();
            }
            if(ModelState.IsValid){
                try{
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                    return View("Index", await _context.Veterinarias.ToListAsync());
                }catch(DbUpdateConcurrencyException){
                    throw;
                }
            }
            return View("Editar", model);
        }

        [HttpGet]
        [Authorize(Roles = "Admin_Edit_Del")]
        public async Task<IActionResult> Editar(int? Id){
            if(Id == null){
                return NotFound();
            }
            var veter = await _context.Veterinarias.FindAsync(Id);
            if(veter == null){
                return NotFound();
            }
            return View(veter);
        }
        [Authorize(Roles = "Admin_Agregar")]
        public IActionResult Agregar()
        {
            return View(new Veterinaria());
        }
        [HttpPost]
        public async Task<IActionResult> Guardar(Veterinaria model)
        {
            if (ModelState.IsValid)
            {
                _context.Veterinarias.Add(model);
                await _context.SaveChangesAsync();
                return View("Index", await _context.Veterinarias.ToListAsync());
            }
            return View("Agregar", model);
        }
        public async Task<IActionResult> Index()
        {
            var veter = await _context.Veterinarias.ToListAsync();
            return View(veter);
        }
        [Authorize]
        public async Task<IActionResult> Details(int Id)
        {
            var veter = await _context.Veterinarias.Where(x => x.Id == Id).Include(x => x.Noticias).FirstAsync();
            return View(veter);
        }
        [Authorize]
        public async Task<IActionResult> Find(string producto)
        {
            List<Veterinaria> listVet = new List<Veterinaria>();
            var veter = await _context.Veterinarias.ToListAsync();
            bool enc = false;
            foreach (var item in veter)
            {
                if (item.Nombre.ToLower().Contains(producto.ToLower()))
                {
                    enc = true;
                    listVet.Add(item);
                }
            }
            if (enc == true)
            {
                return View("Index", listVet);
            }
            else
            {
                ViewData["Message"] = "La búsqueda no coincide con ninguno de nuestros productos";
                return View("Notification");
            }
        }
        [Authorize(Roles = "Admin_Edit_Del")]
        public async Task<IActionResult> Delete(int id){
            var veter = await _context.Veterinarias.FindAsync(id);
            if(veter == null){
                return NotFound();
            }
            _context.Remove(veter);
            await _context.SaveChangesAsync();
            return View("Index", await _context.Veterinarias.ToListAsync());
        }
    }
}

ViewComponents/NoticiasViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Practica_2.Models;

namespace Practica_2.ViewComponents
{
    public class NoticiasViewComponent : ViewComponent
    {
        public List<Noticias> listNoticias = null;
        public NoticiasViewComponent(){
            var jsonString = System.IO.File.ReadAllText("Models/Noticias.json");
            listNoticias = JsonConvert.DeserializeObject<List<Noticias>>(jsonString);

        }
        public async Task<IViewComponentResult> InvokeAsync(int num = 0){
            return View(listNoticias.Take(num).ToList());
        }
    }
}

Views/Vet/Agregar.cshtml
@model Practica_2.Models.Veterinaria
<form asp-controller="Vet" asp-action="Guardar" method="POST">
 @Html.EditorFor(Model => Model)
</form>

Views/Vet/Details.cshtml
@model Practica_2.Models.Veterinaria
@section styles{
    <link rel="stylesheet" href="noticia_style.css" type="text/css">
}
<div class="row" >
    <h1 style="margin-left: 45%;">@Model.Nombre</h1>
    <br><br><br>
</div>
<div class="row" >
  <img style="margin-left: 40%;" src="@Model.ImageDetail" class="imagen" alt="...">
</div>
@section Rigth{
 <div class="col-md-14">
      <div class="card-body">
        <p class="card-text">@Model.Descripcion</p>
        <p class="card-text"><small class="text-muted">Aplicable a: @Model.Aplicabilidad - @Model.Modo</small></p>
        <div class="accordion" id="accordionExample">
            <div class="card">
                    <div class="card-header" id="headingOne">
                        <h2 class="mb-0">
                            <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne"
                                aria-expanded="true" aria-controls="collapseOne">
                                Formulación
                            </button>
                        </h2>
                    </div>

                    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne"
                        data-parent="#accordionExample">
                        <div class="card-body">
                            @Model.Formulacion
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header" id="headingTwo">
                        <h2 class="mb-0">
                            <button class="btn btn-link collapsed" type="button" data-toggle="collapse"
                                data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                Indicaciones
                            </button>
                        </h2>
                    </div>
                    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                        <div class="card-body">
                            @Model.Indicaciones
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header" id="headingThree">
                        <h2 class="mb-0">
                            <button class="btn btn-link collapsed" type="button" data-toggle="collapse"
                                data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                Dosis y Administración
                            </button>
                        </h2>
                    </div>
                    <div id="collapseThree" class="collapse" aria-labelledby="headingThree"
                        data-parent="#accordionExample">
                        <div class="card-body">
                            @Model.DosisAdm
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header" id="headingFour">
                        <h2 class="mb-0">
                            <button class="btn btn-link collapsed" type="button" data-toggle="collapse"
                                data-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                                Presentación Comercial
                            </button>
                        </h2>
                    </div>
                    <div id="collapseFour" class="collapse" aria-labelledby="headingFour"
                        data-parent="#accordionExample">
                        <div class="card-body">
                            @Model.Presentacion
                        </div>
                    </div>
                </div>
        </div>
        <a href="/Vet" class="btn btn-outline-dark" style="margin-top: 12px;">Regresar</a>
      </div>
      
    </div>
}
@section Footer{
    @Html.Partial("Noticias", Model)
}

Views/Vet/Editar.cshtml
@model Practica_2.Models.Veterinaria
<form asp-controller="Vet" asp-action="Editar" method="POST">
 @Html.EditorFor(Model => Model)
</form>

Views/Vet/Index.cshtml
@model List<Practica_2.Models.Veterinaria>
<div class="row">
  @foreach (var item in Model)
  {
    <div class="col-md-4" style="margin-top: 50px;">
      <div class="card mb-5">
        <div class="card-header">
          <button onclick="deleteVet(@item.Id)" type="button" class="m-0 close" data-dismiss="toast" aria-label="Close"/>
          <span aria-hidden="true">&times;</span>
        </div>
        <img src="@item.Image" class="card-img-top" alt="...">
        <div class="card-body">
          <strong>
            <h5 class="card-title">@item.Nombre</h5>
          </strong>
          <p class="card-text">@item.Descripcion</p>
          <a href="/Vet/Details/@item.Id" class="btn btn-outline-info">Ver más...</a>
          <a href="#" onclick="loadNoticias(@item.Id, event)" class="btn btn-outline-success">Noticias</a>
          <a href="/Vet/Editar/@item.Id" class="btn btn-outline-info">Editar</a>
        </div>
      </div>
    </div>
  }
</div>
@section Rigth{
<div class="container">
  <h2 align="center"><b>Buscar Productos:</b></h2>
  <h3>Por especie</h3>
  <div class="list-group" style="margin-bottom: 20px;">
    <a href="#" class="list-group-item list-group-item-action">Aves de combate</a>
    <a href="#" class="list-group-item list-group-item-action">Aves de corral</a>
    <a href="#" class="list-group-item list-group-item-action">Camarones</a>
    <a href="#" class="list-group-item list-group-item-action">Camélidos</a>
    <a href="#" class="list-group-item list-group-item-action">Caninos</a>
    <a href="#" class="list-group-item list-group-item-action">Caprinos</a>
    <a href="#" class="list-group-item list-group-item-action">Conejos</a>
    <a href="#" class="list-group-item list-group-item-action">Cuyes</a>
    <a href="#" class="list-group-item list-group-item-action">Equinos</a>
    <a href="#" class="list-group-item list-group-item-action">Felinos</a>
  </div>
  <h3>Categoría Comercial</h3>
  <div class="list-group" style="margin-bottom: 20px;">
    <a href="#" class="list-group-item list-group-item-action">Antibióticos</a>
    <a href="#" class="list-group-item list-group-item-action">Suplementos Inyectables</a>
    <a href="#" class="list-group-item list-group-item-action">Antiparasitarios</a>
    <a href="#" class="list-group-item list-group-item-action">Anabólicos</a>
    <a href="#" class="list-group-item list-group-item-action">Antiinflamatorios</a>
    <a href="#" class="list-group-item list-group-item-action">Hormonales</a>
    <a href="#" class="list-group-item list-group-item-action">Anestésicos</a>
    <a href="#" class="list-group-item list-group-item-action">Nutricionales</a>
    <a href="#" class="list-group-item list-group-item-action">Otros</a>
  </div>
  <h3>Por División Comercial</h3>
  <div class="list-group">
    <a href="#" class="list-group-item list-group-item-action">Agrovet</a>
    <a href="#" class="list-group-item list-group-item-action">Avivet</a>
    <a href="#" class="list-group-item list-group-item-action">Equestria</a>
    <a href="#" class="list-group-item list-group-item-action">Nutrovet</a>
    <a href="#" class="list-group-item list-group-item-action">Petmedica</a>
  </div>
</div>
@await Component.InvokeAsync("Noticias", new {num = 2})
}
<div class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">¡Hoy en día!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="div_noticias">
        <div class="spinner-border mx-auto" role="modal-body">

        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

Views/Vet/Noticias.cshtml
@model Practica_2.Models.Veterinaria
<div class="container">
    <h3> Noticias Recientes
    </h3>
    @foreach (var item in Model.Noticias)
    {
        <div class="card" style="margin-bottom: 50px;">
            <div class="card-body">
                <h5 class="card-title">@item.Titulo</h5>
                <p class="card-text">@item.Descripcion</p>
                <p class="card-text"><small class="text-muted">@item.Posteo</small></p>
            </div>
            <img class="card-img-bottom" src="/resources/noticia3.jpg" alt="Card image cap">
        </div>
    }
    <div class="bg-light p-2">
        <form asp-controller="Noticias" asp-action="Guardar" method="POST">
            <div class="d-flex flex-row user-info"><img class="rounded-circle" src="https://previews.123rf.com/images/rastudio/rastudio1708/rastudio170809958/84944028-icono-de-l%C3%ADnea-de-vector-de-noticias-global-aislado-sobre-fondo-blanco-icono-de-l%C3%ADnea-de-noticias-gl.jpg"
                        width="40">
                    <div class="d-flex flex-column justify-content-start ml-2"><span
                            class="d-block font-weight-bold name">User</span><span class="date text-black-50">Shared
                            publicly</span></div>
                </div>
            <input type="hidden" name="VeterinariaId" value="@Model.Id" />
            <div class="d-flex flex-row align-items-start">
                <input name="Titulo" type="text" class="form-control ml-1 shadow-none textarea" placeholder="Encabezado"/>
            </div>
            <div class="d-flex flex-row align-items-start">
                <textarea placeholder="Descripción" name="Descripcion" class="form-control ml-1 shadow-none textarea">

                            </textarea>
            </div>
            <div class="mt-2 text-right">
                <button class="btn btn-primary btn-sm shadow-none" type="submit">Enviar noticia</button>
                <button class="btn btn-outline-primary btn-sm ml-1 shadow-none" type="button">Cancel</button>
            </div>
        </form>
    </div>

</div>

Views/Vet/Notification.cshtml
<div class="container">
    <div class="alert alert-danger" align="center" role="alert">
        <p class="h2"><strong>@ViewData["Message"]</strong></p>
        <img src="~/resources/notfound.png" alt="..." style="margin-top: 20px;">
    </div>
</div>